# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Runner' do
  use_frameworks!

  # Pods for Runner
  pod 'Firebase/Core'
  
  # Add any other necessary pods here

end
